name: unboundbible
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path:
  sqflite:
  sqflite_common_ffi:    # for desktop
  desktop_window: ^0.4.0 # for desktop

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ 
