name: unboundbible
description: Unbound Bible Flutter Edition
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path: ^1.8.2
  path_provider: ^2.0.11
  provider: ^6.0.5
  sqlite3_flutter_libs: ^0.5.12
  sqlite3: ^1.9.1
  desktop_window: ^0.4.0
  mobx: ^2.1.3  
  flutter_mobx: ^2.0.6+5

# go_router: ^5.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: 
  mobx_codegen: 

flutter:
  uses-material-design: true
  assets:
    - assets/databases/
