name: unboundbible
description: Unbound Bible Flutter Edition
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  desktop_window: ^0.4.0
  flutter_riverpod: ^2.1.3
  go_router: ^6.0.2
  path: ^1.8.2
  path_provider: ^2.0.11
  shared_preferences: ^2.0.18 
  sqlite3: ^1.9.1
  sqlite3_flutter_libs: ^0.5.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/databases/
