name: unboundbible
description: Unbound Bible Flutter Edition
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  desktop_window: ^0.4.0
  go_router: ^9.0.2
  path: ^1.8.2
  path_provider: ^2.0.11
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  get_it: ^7.6.7
  shared_preferences: ^2.0.18 
  sqlite3: ^2.0.0
  sqlite3_flutter_libs: ^0.5.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/databases/
    - assets/translations/    
